#ifndef __COMMON_STATUS_H__
#define __COMMON_STATUS_H__

typedef enum {
	OK = 0,
	ERROR_NULL_POINTER = 1,
	ERROR_INITIALIZING_SOCKET = 2,
	ERROR_DESTROYING_SOCKET = 3,
	ERROR_GETADDRINFO = 4,
	ERROR_BINDING_SOCKET = 5,
	ERROR_WHILE_LISTENING = 6,
	ERROR_ACCEPTING_SOCKET = 7,
	ERROR_CONNECTING_SOCKET = 8,
	ERROR_SOCKET_SHUTDOWN = 9,
	SOCKET_CLOSED = 10,
	ERROR_SOCKET_RECV = 11,
	ERROR_SOCKET_SEND = 12,
	ERROR_BUFFER_READ = 13,
	ERROR_CYPHER_INIT = 14,
	ERROR_BUFFER_INIT = 15,
	ERROR_CYPHER_DIGEST = 16,
	ERROR_BUFFER_GET = 17,
	ERROR_CYPHER_UNKNOWN_METHOD = 18,
	ERROR_ARGS = 19
} status_t;

#endif
