#ifndef _CLIENT_CONFIG_H__
#define _CLIENT_CONFIG_H__

#define CLIENT_FAMILY_TYPE AF_INET
#define CLIENT_SOCKET_TYPE SOCK_STREAM
#define CLIENT_PROTOCOL IPPROTO_TCP
#define CLIENT_FLAGS AI_PASSIVE

#endif
