#ifndef _SERVER_CONFIG_H__
#define _SERVER_CONFIG_H__

#define SERVER_FAMILY_TYPE AF_INET
#define SERVER_SOCKET_TYPE SOCK_STREAM
#define SERVER_PROTOCOL IPPROTO_TCP
#define SERVER_FLAGS AI_PASSIVE

#endif
